### ISSUE TITLE
AMO opens in the container

### ISSUE THREAD

**Issue by ShintoPlasm** [containers-everywhere/contain-google#21]
When searching in Google from FF's address bar, the Google search page opens correctly in the container. I have set search results from Google to open in a new window, so I don't lose the search page because of Google Container.

However, results from https://addons.mozilla.org/ (AMO) seem to consistently open *inside* the Google Container instead of opening in a new window *outside* the container.

I have Firefox Multi-Account Containers installed, but not Temporary Containers (which I understand from other reports can cause some problems with your add-on).

**Comment by ShintoPlasm** [comment]
![amo](https://user-images.githubusercontent.com/35544416/40640018-6aec8ea4-6314-11e8-8cfa-98295ece5fb7.PNG)

**Comment by Perflyst** [comment]
Thank you for reporting this issue.

The problem is, that an addon is not allowed to cancel requests to addons.mozilla.org.
All container addons (including Multi Account Containers) has the same problem.

We could include this, but you would have to add a hidden about:config rule which can be misused by other addons to modify the AMO website.

**Comment by ShintoPlasm** [comment]
@Perflyst Ah, so it's _that_ annoying little restriction; I thought it was a domain you missed out in your extension. Thanks for clarifying!

**Comment by Perflyst** [comment]
If you have more questions feel free to open a new issue!
