### ISSUE TITLE
Enable back after clicking on search result

### ISSUE THREAD

**Issue by mjedmonds** [containers-everywhere/contain-google#8]
When using google search, clicking on a link closes the Google container tab and opens the link in a new tab. This effectively disables going back to search results.

Is it possible to populate the newly opened tab's back button with the google search to maintain this functionality?

**Comment by Perflyst** [comment]
This is out of scope for this addon. You could click the search result middle mouse or make further finer settings with [Temporary Containers](https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/).

See #4

**Comment by janopae** [comment]
@Perflyst I totally understand that merging the history of two tabs could be complicated and is considered out of scope for the project. But I thought if the extension could at least stop closing the old tab when clicking a link that opens in a Google tab?

I think, the fact that the old tab is closed but you still have no possibility to go back is very confusing. I first thought this was some new sort oft "back button hijacking" that the websites implemented to prevent you from leaving the page.

There is no real sign on wether you lose the current tab when clicking a link or not - you have to keep all Google URLs in mind in order to know which links you have to middle-click in order to not lose the current tab.

As far as I can think, the improvement of not closing the tab only meant removing code - the one that closes the current tab when clicking a link - so could this be considered in scope for the project?
